version: "2.2"
services:
  potential_api:
    image: hitalos/laravel:latest
    container_name: potential_api
    ports:
      - 88:80
    volumes:
      - ./api:/var/www
    links:
      - potential_db
      - potential_db_test
    environment:
      DB_HOST: potential_db
      DB_DATABASE: potential
      DB_USERNAME: potential-dev
      DB_PASSWORD: p455w0rd
      DB_CONNECTION: mysql
    command: >
      sh -c "echo -e 'zend_extension=xdebug
        xdebug.idekey=PHPSTORM
        xdebug.remote_host=172.18.0.1
        xdebug.remote_enable=1
        xdebug.remote_port=9000
        xdebug.remote_autostart=1
        xdebug.remote_connect_back=0
        xdebug.remote_handler=dbgp
        xdebug.idekey=PHPSTORM' > /usr/local/etc/php/conf.d/xdebug.ini &&
        php artisan migrate &&
        php artisan serve --port=80 --host=0.0.0.0"

  potential_db:
    image: mysql:5.7
    container_name: potential_db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: potential
      MYSQL_USER: potential-dev
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: root

  potential_db_test:
    image: mysql:5.7
    container_name: potential_db_test
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: potential
      MYSQL_USER: potential-dev
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: root