version: "2.2"
services:
  potential_api:
    image: hitalos/laravel:latest
    container_name: potential_api
    ports:
      - 88:80
    volumes:
      - ./api:/var/www
    links:
      - potential_db
      - potential_db_test
    environment:
      DB_HOST: potential_db
      DB_DATABASE: potential
      DB_USERNAME: potential-dev
      DB_PASSWORD: p455w0rd
      DB_CONNECTION: mysql
    command: >
      sh -c "
        php artisan key:generate &&
        php artisan migrate &&
        php artisan serve --port=80 --host=0.0.0.0"

  potential_db:
    image: mysql:5.7
    container_name: potential_db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: potential
      MYSQL_USER: potential-dev
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: root

  potential_db_test:
    image: mysql:5.7
    container_name: potential_db_test
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: potential
      MYSQL_USER: potential-dev
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: root

  potential_front:
      image: node:12
      container_name: potential_front
      tty: true
      ports:
        - 3000:3000
      volumes:
        - ./front:/var/www
      links:
        - potential_api
      command: >
        sh -c "cd /var/www && npm i && npm start"